services:
  mongo:
    image: mongo:6.0.14
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database_resources:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: app